# Generated by Django 5.2.1 on 2026-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], default='nuevo', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('nuevo', 'Nuevo'), ('usado', 'Usado')], default='disponible', max_length=20),
        ),
    ]
