# Generated by Django 5.2.1 on 2026-05-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_vehiculo_condicion_vehiculo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=20),
        ),
    ]
