# Generated by Django 5.2.1 on 2026-05-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_vehiculo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta de Venta (Consumidor Final)'), ('factura', 'Factura (Con RUC)')], default='boleta', max_length=10)),
                ('identificacion', models.CharField(help_text='Cédula (10) o RUC (13)', max_length=13)),
                ('nombre_razon_social', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('direccion_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, help_text='IVA 15%', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventario.vehiculo', verbose_name='Vehículo Vendido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
